### ISSUE TITLE
Add new "settings" table

### ISSUE THREAD

**Issue by meaudotme** [untapped-inc/sema-database#1]
We need a `settings` table to be able to store admin configuration preferences. Here are the necessary columns:

- `id` - primary key bigint(20) unsigned NOT NULL AUTO_INCREMENT
- `name` - varchar (unique and indexed)
- `value` - varchar
- `description` - longtext
- `created_at` - timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
- `updated_at` - timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

We'll make sure to auto populate it with default values. Here are the proposed configurations to start it with:

- `water_product_category_id` - The ID of the product category that the SWE considers as a water product. The idea is that they could really name it however they want (in their language) for the interface
- `anonymous_customer_type_id` - The ID of the customer type that the SWE considers as an anonymous customer. Same reason as above
- ~~`default_liquid_unit` - The unit measure to be used for liquid products by default on the reports screens of the POS and the back office clients. Default value: `liters`~~
- `default_unit_system` - The unit system to display reports and unit measures in. Possible values: `metric` or `imperial`. Default: `metric`.

**Comment by meaudotme** [comment]
For the moment, all those settings apply to all kiosks. Those are company-wide settings. For kiosk-level settings, we'll create a new table called `kiosk_settings`, which will map settings from the `settings` table to specific kiosks.

**Comment by meaudotme** [comment]
Instead of `default_liquid_unit`, we'll use `default_unit_system`.

I realized, it's not just about the unit measure, it's about the system being used: `metric` or `imperial`?

**Comment by jeanniton-mnr** [comment]
I think `water_product_category_id` and `anonymous_customer_type_id` should be implemented at the developer level (nowhere else than in code and logic). 
   
It makes sense to implement the unit as being imperial or metric. But I think implementing it as a `volume_unit` and a `weight_unit` separately with all possible values/unit is very practical.
    
At last, I would implement **settings** only on the client side. And now, the API would only have to return a consistent `values`/units` in imperial or metric for example. Then, you can implement a module/library that converts between different types of units on the client side (from the metric or imperial units returned by the API)

After that, everything looks good.

**Comment by meaudotme** [comment]
Decided to add a "title" column too. Kept the name as a slug/key.
